# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: UiPathPack@2
  inputs:
    versionType: AutoVersion
    #version: '1.0.0' # Required when versionType == ManualVersion
    projectJsonPath: '$(Build.SourcesDirectory)\uipath-cicd-sample'
    outputPath: '$(Build.ArtifactStagingDirectory)\Packages\uipath-cicd-sample'
    #outputType: 'None' # Options: Process, Library, Tests, Objects, None
    orchestratorConnection: 'uat' # Service connection to UiPath Orchestrator

