# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- name: System.Debug
  value: True


trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: dir $(Build.SourcesDirectory)


- task: UiPathPack@2
  inputs:
    versionType: AutoVersion
    #version: '1.0.0' # Required when versionType == ManualVersion
    projectJsonPath: '$(Build.SourcesDirectory)'
    outputPath: '$(Build.ArtifactStagingDirectory)\output'
    #outputType: 'None' # Options: Process, Library, Tests, Objects, None
    orchestratorConnection: 'uat' # Service connection to UiPath Orchestrator

- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'uat' # Service connection to UiPath Orchestrator
    packagesPath: '$(Build.ArtifactStagingDirectory)\output'
    folderName: 'Default'
    environments: 'test-machines' # Optional
    